In [2]:
import numpy as np

In [4]:
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [14]:
A,B

(array([[2, 3],
        [4, 5]]),
 array([[6, 7],
        [8, 9]]))

In [16]:
A.shape, B.shape

((2, 2), (2, 2))

In [17]:
# Linear Algebra
# 1 
# det(A)=(2)(4)−(3)(5)=8-15=−7
det = np.linalg.det(A)
det

np.float64(-2.0)

In [13]:
# Calculating the inverse of a matrix
#2
# inverse(A) = 1/det(A) * [[d, -b], [-c, a]]
# inverse(A) = 1/(-2) * [[5, -3], [-4, 2]] = [[-2.5, 1.5], [2, -1]]
inverse_matrix = np.linalg.inv(A)
inverse_matrix

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [19]:
# 3
# dot product
dotp = np.dot(A, B)
dotp

array([[36, 41],
       [64, 73]])

In [22]:
#4
# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors

(array([-0.27491722,  7.27491722]),
 array([[-0.79681209, -0.49436913],
        [ 0.60422718, -0.86925207]]))

In [24]:
#5
#Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(A)
U,S,V

(array([[-0.48992502, -0.87176457],
        [-0.87176457,  0.48992502]]),
 array([7.34342046, 0.27235265]),
 array([[-0.60828716, -0.79371704],
        [ 0.79371704, -0.60828716]]))

In [26]:
#Calculus
#6
x = np.array([1, 2, 3, 4, 5])
y = 2 * x + 3
dy_dx = np.gradient(y, x)
print("x значения:", x)
print("f(x) значения:", y)
print("Численная производная dy/dx:", dy_dx)

x значения: [1 2 3 4 5]
f(x) значения: [ 5  7  9 11 13]
Численная производная dy/dx: [2. 2. 2. 2. 2.]


In [30]:
#7
#Definite Integral using the trapezoidal rule
area = np.trapezoid(y, x)

print("Площадь под кривой:", area)

Площадь под кривой: 36.0


In [32]:
# 8
# sin, cos, tg, ctg
c = np.sin(x)
sin_c = np.sin(x)
cos_c = np.cos(x)
tan_c = np.tan(x)
sin_c, cos_c, tan_c

(array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219]),
 array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501]))

In [34]:
# 9
# Natural logarithm
natural_log = np.log(x)
natural_log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [41]:
#10
# integral(Simpson's rule)
from scipy.integrate import simpson
x_values = np.array([3, 4, 5, 6, 7]) 
def linear_function(x):
    return 2 * x + 3
y_values = linear_function(x_values)
integral_result = simpson(y_values, x=x_values)
print("Результат интегрирования:", integral_result)

Результат интегрирования: 52.0


In [43]:
## Statistics
# 11
# the middle value in a sorted array
median = np.median(x)
median

np.float64(3.0)

In [48]:
#12
## average value of all the elements in the array
dat = np.array([23, 45, 87, 12, 90])
average_value = np.average(dat)
average_value = int(average_value)
average_value


51

In [50]:
#13
#Dispersion
variance = np.var(dat)
variance


np.float64(1031.44)

In [53]:
#14
# Standard Deviation
std_deviation = np.std(dat)
std_deviation

np.float64(32.11603960640228)

In [55]:
#15
#Correlation
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5, 6])
correlation = np.corrcoef(data1, data2)[0, 1]
print("Коэффициент корреляции между data1 и data2:", correlation)


Коэффициент корреляции между data1 и data2: 1.0
